-- Core app tables, recovered exactly from PLAYGROUND_DB.DQ_APP via GET_DDL.
-- Ordered so foreign-key targets are created first. Idempotent.

CREATE TABLE IF NOT EXISTS ASSETS (
	ID VARCHAR(36) NOT NULL,
	ASSET_TYPE VARCHAR(50) NOT NULL,
	DATABASE_NAME VARCHAR(255) NOT NULL,
	SCHEMA_NAME VARCHAR(255),
	TABLE_NAME VARCHAR(255),
	COLUMN_NAME VARCHAR(255),
	FQN VARCHAR(1024) NOT NULL,
	OWNER VARCHAR(255),
	COMMENT VARCHAR(16777216),
	ROW_COUNT NUMBER(38,0),
	SIZE_BYTES NUMBER(38,0),
	RAW_METADATA VARIANT,
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	LAST_SCANNED_AT TIMESTAMP_TZ(9),
	UNIQUE (FQN),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RULE_DEFINITIONS (
	ID VARCHAR(36) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	CATEGORY VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(16777216) NOT NULL,
	CHECK_KIND VARCHAR(20) NOT NULL,
	HANDLER_KEY VARCHAR(100),
	SQL_TEMPLATE VARCHAR(16777216),
	PARAMETERS_SCHEMA VARIANT,
	DEFAULT_THRESHOLD_CONFIG VARIANT,
	DEFAULT_SEVERITY VARCHAR(20) NOT NULL,
	ALLOWED_SCOPES VARIANT NOT NULL,
	SOURCE VARCHAR(20) NOT NULL DEFAULT 'system',
	STATUS VARCHAR(20) NOT NULL DEFAULT 'active',
	INSTANCE_COUNT NUMBER(38,0) NOT NULL DEFAULT 0,
	APPROVAL_COUNT NUMBER(38,0) NOT NULL DEFAULT 0,
	OWNER VARCHAR(255),
	CREATED_BY VARCHAR(255),
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SCANS (
	ID VARCHAR(36) NOT NULL,
	ASSET_ID VARCHAR(36) NOT NULL,
	CONNECTION_ID VARCHAR(36),
	SCAN_TYPE VARCHAR(20) NOT NULL DEFAULT 'metadata',
	STATUS VARCHAR(20) NOT NULL DEFAULT 'pending',
	STARTED_AT TIMESTAMP_TZ(9),
	COMPLETED_AT TIMESTAMP_TZ(9),
	RULES_CHECKED NUMBER(38,0) DEFAULT 0,
	FINDINGS_COUNT NUMBER(38,0) DEFAULT 0,
	ERROR_MESSAGE VARCHAR(1024),
	SCAN_CONFIG VARIANT,
	SCAN_RESULTS VARIANT,
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID),
	FOREIGN KEY (ASSET_ID) REFERENCES PLAYGROUND_DB.DQ_APP.ASSETS(ID)
);

CREATE TABLE IF NOT EXISTS RULE_INSTANCES (
	ID VARCHAR(36) NOT NULL,
	DEFINITION_ID VARCHAR(36) NOT NULL,
	SCOPE VARCHAR(20) NOT NULL,
	DATABASE_NAME VARCHAR(255) NOT NULL,
	SCHEMA_NAME VARCHAR(255),
	TABLE_NAME VARCHAR(255),
	TARGET_CONFIG VARIANT NOT NULL,
	THRESHOLD_CONFIG VARIANT,
	SEVERITY VARCHAR(20) NOT NULL,
	RULE_SQL VARCHAR(16777216),
	STATUS VARCHAR(20) NOT NULL DEFAULT 'active',
	FINGERPRINT VARCHAR(64) NOT NULL,
	IS_ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
	EDITED_BY_HUMAN BOOLEAN NOT NULL DEFAULT FALSE,
	JIRA_TICKET VARCHAR(100),
	REJECTION_REASON VARCHAR(16777216),
	OWNER VARCHAR(255) NOT NULL,
	CREATED_BY VARCHAR(255),
	SOURCE_RUN_ID VARCHAR(36),
	VERSION NUMBER(38,0) NOT NULL DEFAULT 1,
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	APPROVED_AT TIMESTAMP_TZ(9),
	REJECTED_AT TIMESTAMP_TZ(9),
	PRIMARY KEY (ID),
	FOREIGN KEY (DEFINITION_ID) REFERENCES PLAYGROUND_DB.DQ_APP.RULE_DEFINITIONS(ID)
);

CREATE TABLE IF NOT EXISTS FINDINGS (
	ID VARCHAR(36) NOT NULL,
	ASSET_ID VARCHAR(36) NOT NULL,
	SCAN_ID VARCHAR(36) NOT NULL,
	INSTANCE_ID VARCHAR(36),
	TITLE VARCHAR(512) NOT NULL,
	DESCRIPTION VARCHAR(16777216) NOT NULL,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'detected',
	SEVERITY VARCHAR(20) NOT NULL,
	CONTEXT VARIANT,
	EVIDENCE VARIANT,
	ASSIGNED_TO VARCHAR(255),
	RESOLUTION_NOTES VARCHAR(16777216),
	DETECTED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	VALIDATED_AT TIMESTAMP_TZ(9),
	RESOLVED_AT TIMESTAMP_TZ(9),
	CLOSED_AT TIMESTAMP_TZ(9),
	UPDATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	-- Incident lifecycle: one row per (INSTANCE_ID, ASSET_ID), persists across scans.
	FIRST_DETECTED_AT   TIMESTAMP_TZ(9),
	LAST_SEEN_AT        TIMESTAMP_TZ(9),
	LAST_SCAN_ID        VARCHAR(36),
	REOPENED_COUNT      NUMBER(38,0) DEFAULT 0,
	CURRENT_FAIL_COUNT  NUMBER(38,0),
	CURRENT_TOTAL_COUNT NUMBER(38,0),
	FAIL_HISTORY        VARIANT,
	PRIMARY KEY (ID),
	FOREIGN KEY (ASSET_ID) REFERENCES PLAYGROUND_DB.DQ_APP.ASSETS(ID),
	FOREIGN KEY (SCAN_ID) REFERENCES PLAYGROUND_DB.DQ_APP.SCANS(ID),
	FOREIGN KEY (INSTANCE_ID) REFERENCES PLAYGROUND_DB.DQ_APP.RULE_INSTANCES(ID)
);

CREATE TABLE IF NOT EXISTS MUTES (
	ID          VARCHAR(36) NOT NULL,
	INSTANCE_ID VARCHAR(36) NOT NULL,
	ASSET_ID    VARCHAR(36) NOT NULL,
	MUTED_UNTIL TIMESTAMP_TZ(9) NOT NULL,
	REASON      VARCHAR(16777216),
	MUTED_BY    VARCHAR(255),
	CREATED_AT  TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID),
	FOREIGN KEY (INSTANCE_ID) REFERENCES PLAYGROUND_DB.DQ_APP.RULE_INSTANCES(ID),
	FOREIGN KEY (ASSET_ID)    REFERENCES PLAYGROUND_DB.DQ_APP.ASSETS(ID)
);

CREATE TABLE IF NOT EXISTS RULE_EXECUTIONS (
	ID VARCHAR(36) NOT NULL,
	INSTANCE_ID VARCHAR(36) NOT NULL,
	SCAN_ID VARCHAR(36),
	RUN_ID VARCHAR(36),
	STATUS VARCHAR(20) NOT NULL,
	EVIDENCE VARIANT,
	EXECUTED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID),
	FOREIGN KEY (INSTANCE_ID) REFERENCES PLAYGROUND_DB.DQ_APP.RULE_INSTANCES(ID),
	FOREIGN KEY (SCAN_ID) REFERENCES PLAYGROUND_DB.DQ_APP.SCANS(ID)
);

CREATE TABLE IF NOT EXISTS AGENT_RUNS (
	ID VARCHAR(36) NOT NULL,
	CONNECTION_ID VARCHAR(36),
	BATCH_ID VARCHAR(36),
	BATCH_INDEX NUMBER(38,0) DEFAULT 0,
	DATABASE_NAME VARCHAR(255) NOT NULL,
	SCHEMA_NAME VARCHAR(255) NOT NULL,
	TABLE_NAME VARCHAR(255) NOT NULL,
	STATUS VARCHAR(30) NOT NULL DEFAULT 'pending',
	SCAN_ID VARCHAR(36),
	STARTED_AT TIMESTAMP_TZ(9),
	COMPLETED_AT TIMESTAMP_TZ(9),
	FINDINGS_COUNT NUMBER(38,0) DEFAULT 0,
	AI_RULES_COUNT NUMBER(38,0) DEFAULT 0,
	ERROR_MESSAGE VARCHAR(1024),
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	INSTANCE_REVIEW_STATE VARIANT,
	PRIMARY KEY (ID),
	FOREIGN KEY (SCAN_ID) REFERENCES PLAYGROUND_DB.DQ_APP.SCANS(ID)
);

CREATE TABLE IF NOT EXISTS AGENT_TASKS (
	ID VARCHAR(36) NOT NULL,
	RUN_ID VARCHAR(36) NOT NULL,
	AGENT_NAME VARCHAR(100) NOT NULL,
	STATUS VARCHAR(20) NOT NULL DEFAULT 'pending',
	STARTED_AT TIMESTAMP_TZ(9),
	COMPLETED_AT TIMESTAMP_TZ(9),
	OUTPUT VARIANT,
	ERROR_MESSAGE VARCHAR(16777216),
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID),
	FOREIGN KEY (RUN_ID) REFERENCES PLAYGROUND_DB.DQ_APP.AGENT_RUNS(ID)
);

CREATE TABLE IF NOT EXISTS RECOMMENDATION_CACHE (
	ID VARCHAR(36) NOT NULL,
	CACHE_KEY VARCHAR(255) NOT NULL,
	RULE_CODE VARCHAR(100) NOT NULL,
	DATA_TYPE VARCHAR(100) NOT NULL DEFAULT '',
	EXPLANATION_TEMPLATE VARCHAR(16777216) NOT NULL,
	SQL_TEMPLATE VARCHAR(16777216) NOT NULL,
	CONFIDENCE NUMBER(38,0) DEFAULT 75,
	IMPACT VARCHAR(16777216),
	HIT_COUNT NUMBER(38,0) DEFAULT 0,
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	UNIQUE (CACHE_KEY),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RULE_CRITIQUE_DROPS (
	ID VARCHAR(36) NOT NULL,
	RUN_ID VARCHAR(36) NOT NULL,
	TABLE_FQN VARCHAR(500) NOT NULL,
	PROPOSAL_NAME VARCHAR(500),
	DEFINITION_ID VARCHAR(500),
	COLUMN_NAME VARCHAR(500),
	TEMPLATE_SHAPE VARCHAR(100),
	EVIDENCE_SCORE NUMBER(38,0),
	IMPACT_SCORE NUMBER(38,0),
	APPROVAL_SCORE NUMBER(38,0),
	MEAN_SCORE FLOAT,
	DROP_REASON VARCHAR(2000),
	PROPOSAL_JSON VARIANT,
	CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	PRIMARY KEY (ID)
);
