-- Idempotent migrations for pre-existing DQ_APP deployments.
-- CREATE TABLE IF NOT EXISTS in 02_tables.sql is a no-op when a table already
-- exists, so columns added after a table was first created must be ALTERed in
-- here. ADD COLUMN IF NOT EXISTS is idempotent — safe to re-run.

-- Multi-source support: which saved connection a run/scan targeted.
ALTER TABLE AGENT_RUNS ADD COLUMN IF NOT EXISTS CONNECTION_ID VARCHAR(36);
ALTER TABLE SCANS ADD COLUMN IF NOT EXISTS CONNECTION_ID VARCHAR(36);

-- ─────────────────────────────────────────────────────────────────────────
-- Incident lifecycle on FINDINGS.
-- Model: one FINDINGS row per (INSTANCE_ID, ASSET_ID) that persists across
-- scans. Each scan UPDATEs / RESOLVEs / REOPENs / CREATEs. See
-- services/scan_finalizer.py for the state machine.
-- ─────────────────────────────────────────────────────────────────────────
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS FIRST_DETECTED_AT TIMESTAMP_TZ(9);
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS LAST_SEEN_AT      TIMESTAMP_TZ(9);
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS LAST_SCAN_ID      VARCHAR(36);
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS REOPENED_COUNT    NUMBER(38,0) DEFAULT 0;
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS CURRENT_FAIL_COUNT  NUMBER(38,0);
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS CURRENT_TOTAL_COUNT NUMBER(38,0);
ALTER TABLE FINDINGS ADD COLUMN IF NOT EXISTS FAIL_HISTORY VARIANT;

-- Backfill: existing rows have DETECTED_AT but no lifecycle timestamps.
UPDATE FINDINGS
SET FIRST_DETECTED_AT = DETECTED_AT
WHERE FIRST_DETECTED_AT IS NULL;
UPDATE FINDINGS
SET LAST_SEEN_AT = COALESCE(UPDATED_AT, DETECTED_AT)
WHERE LAST_SEEN_AT IS NULL;
UPDATE FINDINGS
SET LAST_SCAN_ID = SCAN_ID
WHERE LAST_SCAN_ID IS NULL;

-- Muting: silence a specific (INSTANCE_ID, ASSET_ID) for a window.
-- During a mute, executions still run + RULE_EXECUTIONS still log, but the
-- lifecycle skips update/reopen/create on failure so no new incident surfaces.
CREATE TABLE IF NOT EXISTS MUTES (
    ID VARCHAR(36) NOT NULL,
    INSTANCE_ID VARCHAR(36) NOT NULL,
    ASSET_ID VARCHAR(36) NOT NULL,
    MUTED_UNTIL TIMESTAMP_TZ(9) NOT NULL,
    REASON VARCHAR(16777216),
    MUTED_BY VARCHAR(255),
    CREATED_AT TIMESTAMP_TZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ID),
    FOREIGN KEY (INSTANCE_ID) REFERENCES PLAYGROUND_DB.DQ_APP.RULE_INSTANCES(ID),
    FOREIGN KEY (ASSET_ID)    REFERENCES PLAYGROUND_DB.DQ_APP.ASSETS(ID)
);
